### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by tarekdawey** [mees/hulc2#7]
python hulc2/evaluation/evaluate_policy.py --dataset_path dataset/task_D_D --train_folder real_world_checkpoints/aff_model_single/checkpoints
Global seed set to 0
Traceback (most recent call last):
  File "/home/systemtec/hulc2/hulc2/evaluation/evaluate_policy.py", line 94, in <module>
    main()
  File "/home/systemtec/hulc2/hulc2/evaluation/evaluate_policy.py", line 81, in main
    checkpoints = [Path("epoch=%s.ckpt" % int(chk)) for chk in args.checkpoints.split(",")]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mees** [comment]
Hi there, you are trying to evaluate the real world policy checkpoints on the CALVIN benchmark, that is not supported.
